// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Toaster } from "react-hot-toast";
// import "@/app/globals.css";
// import '@/app/components/lib/auth/amplify-config';


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Toaster position="top-center" />
//         {children}
//       </body>
//     </html>
//   );
// }


import { Inter } from 'next/font/google';
import './globals.css';
import ClientWrapper from './ClientWrapper'; // adjust path

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'CHMOVIES - OTT Admin Control Panel',
  description: 'AWTOX admin panel for OTT Platform',
  icons: {
    icon: { url: '/favicon.ico', type: 'image/x-icon', sizes: '16x16' },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
